// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCicLgmW484UbEsfWIQXvvnjXtD8fVIOtk',
    appId: '1:514524556018:web:2833bd1438883837903e6b',
    messagingSenderId: '514524556018',
    projectId: 'school-course-guide',
    authDomain: 'school-course-guide.firebaseapp.com',
    storageBucket: 'school-course-guide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWP4Pg2ix8b7K1wdwz41BU8ieidd_kHUI',
    appId: '1:514524556018:android:56f876e08ec9346e903e6b',
    messagingSenderId: '514524556018',
    projectId: 'school-course-guide',
    storageBucket: 'school-course-guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6fJ_G8e9mkhpltSFW52K_JiLOrY-g_I',
    appId: '1:514524556018:ios:ac87a59e0c986595903e6b',
    messagingSenderId: '514524556018',
    projectId: 'school-course-guide',
    storageBucket: 'school-course-guide.appspot.com',
    iosBundleId: 'com.example.courseGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6fJ_G8e9mkhpltSFW52K_JiLOrY-g_I',
    appId: '1:514524556018:ios:4cc30e8c6c50bdc4903e6b',
    messagingSenderId: '514524556018',
    projectId: 'school-course-guide',
    storageBucket: 'school-course-guide.appspot.com',
    iosBundleId: 'com.example.courseGuide.RunnerTests',
  );
}
